### ISSUE TITLE
WebSharper.Collections is missing while trying to use UI.Next with Warp

### ISSUE THREAD

**Issue by Kimserey** [intellifactory/websharper.warp#14]
Even after referencing WebSharper.Collections, WebSharper.Collections.min.js isn't generated which makes it impossible to use UI.Next with Warp

**Comment by Tarmil** [comment]
It seems this is a problem since to the introduction of shadow-copying in F# interactive. Warp ensures that all WebSharper assemblies are used, even those not loaded in the current domain, by passing all dlls located in the same directory as WebSharper.Main to the compiler, however shadow-copied assemblies are in separate directories so this doesn't work anymore.

Adding `#r "WebSharper.Collections.dll"` isn't enough because F# interactive is lazy in its referencing: an `#r`'d assembly is loaded reflection-only, and only fully loaded when its code is actually used. So it seems the solution is to `#r` it _and_ to make Warp also pass reflection-only-loaded assemblies to the compiler.

**Comment by Tarmil** [comment]
In the meantime you can run `fsi --shadowcopyreferences-` to ensure that shadow-copying is disabled.
