### ISSUE TITLE
Warp does not seem to recognize contents

### ISSUE THREAD

**Issue by Kimserey** [intellifactory/websharper.warp#16]
I have placed a .css file as a embedded resource under WebSharper.Warp.Test. I can also see the embedded style resource from ILSpy on WebSharper.Warp.Test.exe under \Resources but Warp does not seem to generate any \Content.

**Comment by Tarmil** [comment]
Normally you would need the following in your project code:

``` fsharp
type Style() = inherit Resources.BaseResource("style.css")

[<assembly:Require(typeof<Style>)>]
[<assembly:System.Web.UI.WebResource("style.css", "text/css")>]
do ()
```

However it seems assembly-wide `[<Require>]`s don't work with Warp currently. I have a WIP which can detect that the executing assembly is already compiled with WebSharper and use that metadata instead of running the compiler itself, that should fix this issue at the same time. In the meantime, you can put the `[<Require>]` attribute on your client-side code instead of on the assembly, that also works.

**Comment by Kimserey** [comment]
Is `[<assembly:System.Web.UI.WebResource("style.css", "text/css")>]` needed?
I thought that if the resource is a embedded file, it will automatically concatenate it with the default .css.

**Comment by Tarmil** [comment]
Yes, only resources that have a corresponding `WebResource` attribute are extracted. The reason is that just because you embed a file in your assembly doesn't mean you intend to serve it, so we don't want to publish files that are intended to remain private to the application.

**Comment by Kimserey** [comment]
It makes sense! Thanks for the explanation.
